name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules/.vite
          key: ${{ runner.os }}-build-${{ github.sha }}
